### ISSUE TITLE
Filter by Range

### ISSUE THREAD

**Issue by DavidSHardage** [neon-ninja/QONQR#9]
Is it possible to add in a radius to the map? The user would select a distance (10 miles, 20 miles, 1000 miles, 6000 miles, etc) and click on the map. Then the zones would filter to anything within that range. Similar to this: https://www.calcmaps.com/map-radius/

Thank you!

**Comment by neon-ninja** [comment]
Is it necessary to filter the zones? Would just adding the standard leaflet draw tools suffice? https://leaflet.github.io/Leaflet.draw/docs/examples/full.html

**Comment by DavidSHardage** [comment]
I think that would work. Just some way to see which zones are within range.

**Comment by neon-ninja** [comment]
Note that I already render a blue circle showing nanomissile distance:

https://github.com/neon-ninja/QONQR/blob/master/index.html#L147-L158

**Comment by DavidSHardage** [comment]
Oh, goodness. You do! I did not realize that, but once I looked at the code I realized that it was because my location was not being shared. Apologies! Looks like this is already done. Thank you!
